// Metrics.jsx
import "./Metrics.css";

function Metrics({ metrics }) {
  if (!metrics) return null;

  const classification = metrics.classification || {};

  const metricItems = [
    {
      id: 1,
      title: "Accuracy",
      value:
        classification.accuracy != null ? `${classification.accuracy}%` : "-",
      icon: (
        <svg
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <circle cx="12" cy="12" r="10" />
          <circle cx="12" cy="12" r="6" />
          <circle cx="12" cy="12" r="2" />
        </svg>
      ),
      color: "blue",
    },
    {
      id: 2,
      title: "Precision",
      value:
        classification.precision != null ? `${classification.precision}%` : "-",
      icon: (
        <svg
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
        </svg>
      ),
      color: "green",
    },
    {
      id: 3,
      title: "Recall",
      value: classification.recall != null ? `${classification.recall}%` : "-",
      icon: (
        <svg
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <circle cx="11" cy="11" r="8" />
          <line x1="21" y1="21" x2="16.65" y2="16.65" />
        </svg>
      ),
      color: "orange",
    },
    {
      id: 4,
      title: "F1 Score",
      value:
        classification.f1_score != null ? `${classification.f1_score}%` : "-",
      icon: (
        <svg
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <line x1="18" y1="20" x2="18" y2="10" />
          <line x1="12" y1="20" x2="12" y2="4" />
          <line x1="6" y1="20" x2="6" y2="14" />
        </svg>
      ),
      color: "purple",
    },
    {
      id: 5,
      title: "Inference Time",
      value:
        metrics.inference_time != null ? `${metrics.inference_time} ms` : "-",
      icon: (
        <svg
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
        </svg>
      ),
      color: "red",
    },
    {
      id: 6,
      title: "Model",
      value: classification.model || "-",
      icon: (
        <svg
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96-.44 2.5 2.5 0 0 1 0-3.12 3.5 3.5 0 0 1 0-3.88 2.5 2.5 0 0 1 0-3.12A2.5 2.5 0 0 1 9.5 2z" />
          <path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96-.44 2.5 2.5 0 0 0 0-3.12 3.5 3.5 0 0 0 0-3.88 2.5 2.5 0 0 0 0-3.12A2.5 2.5 0 0 0 14.5 2z" />
        </svg>
      ),
      color: "cyan",
    },
  ];

  return (
    <section className="metrics-section" aria-labelledby="metrics-heading">
      <div className="metrics-header">
        <h2 id="metrics-heading">Model Performance</h2>
        <p>
          Statistical metrics generated by the neural networks running
          verification pipelines.
        </p>
      </div>

      <div className="metrics-grid">
        {metricItems.map((item) => (
          <div key={item.id} className="metric-card">
            <div className="metric-card-inner-glow" aria-hidden="true" />
            <div className={`metric-icon-box ${item.color}`} aria-hidden="true">
              {item.icon}
            </div>
            <div className="metric-details">
              <h4>{item.title}</h4>
              <p className="metric-display-value">{item.value}</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

export default Metrics;
